[package]
name = "rust-perfcnt-bare-metal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.x86]
version = "0.42.1"
features = [ "performance-counter" ]